apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        defaultRules:
          create: false
        alertmanager:
          enabled: true
          alertmanagerSpec:
            alertmanagerConfigSelector:
              matchLabels:
                alertmanagerConfig: email-test
        grafana:
          enabled: true
          adminPassword: admin
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        prometheus:
          prometheusSpec:
            retention: 6h
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 768Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
